spring:
  config:
    activate:
      on-profile: local
  thymeleaf:
    prefix: classpath:templates/views
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.board.common.**

server:
  port: 8080
