database: mysql

spring:
  config:
    activate:
      on-profile: local
  thymeleaf:
    prefix: classpath:templates
  sql:
    init:
      schema-locations: classpath:db/${database}/schema/*.sql #Spring Boot 2.5.0 이전에서는 srping.datasource.schema 속성으로 사용
      data-locations: classpath:db/${database}/data/*.sql     #Spring Boot 2.5.0 이전에서는 srping.datasource.data 속성으로 사용
  datasource:
    url: jdbc:log4jdbc:h2:mem:testdb;MODE=MYSQL
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.board.*.model.entity
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080
